# Generated by Django 3.0.7 on 2020-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Following",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "The follow request is pending approval or deny"),
                            (2, "The follow request is approved"),
                            (3, "The follow request is deny"),
                        ],
                        default=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created"],},
        ),
    ]
