# Generated by Django 3.0.7 on 2020-06-14 17:11

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("following", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="following",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="following",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="following",
            constraint=models.CheckConstraint(
                check=models.Q(
                    _negated=True,
                    follower__exact=django.db.models.expressions.F("followed"),
                ),
                name="you_cannot_follow_yourself",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="following", unique_together={("follower", "followed")},
        ),
    ]
